### ISSUE TITLE
mres calculation mistake at row 398

### ISSUE THREAD

**Issue by ademirci** [kriswiner/MPU9150#1]
I was looking at your MPU9150BasicAHRS.ino file and I noticed that mres calculation at row 398 is wrong. 
It is mRes = 10.*1229./4096 but it should be mres = 12.29 / 4096. Because 1 uT is 0.01 Gauss
I think you made a typing mistake because in the comment you write that 1229 uT is 12.29 Gauss

**Comment by kriswiner** [comment]
Yes, you are correct, but my intention was to convert to milliGauss. Sorry if the comment was confusing!

**Comment by ademirci** [comment]
Is there any special reason you choose to use miliGauss?

**Comment by kriswiner** [comment]
It is easier to display on the Nokia 5100 84 x 48 lcd display I am using if the values are 1) integers, and between 0 and 1000. That's all. I do this with acceleration too.
